id = "git-perfect"
name = "Git Perfect"
version = "1.0.0"
schema_version = 1
authors = ["Karl Hohls <karl@alphadogdigital.co.za>"]
description = "High-performance LSP server for Git Perfect insights"
repository = "https://github.com/KanzenJ/git-perfect"
license = "MIT"
[language_servers.git-perfect-lsp]
name = "git-perfect-lsp"
languages = [
    "TypeScript",
    "JavaScript",
    "TSX",
    "JSX",
    "Rust",
    "PHP",
    "Go",
    "Python",
    "Ruby",
    "HTML",
    "CSS",
    "JSON",
    "TOML",
    "YAML",
    "Markdown",
    "Shell Script"
]
