use zed_extension_api as zed;

struct GitPerfectExtension {
    // State can be kept here if needed
}

impl zed::Extension for GitPerfectExtension {
    fn new() -> Self {
        Self {}
    }

    fn language_server_command(
        &mut self,
        _language_server_id: &zed::LanguageServerId,
        _worktree: &zed::Worktree,
    ) -> Result<zed::Command, String> {
        // Explicitly returns a String error type
        // Query the Node binary bundled inside the Zed editor environment
        let node_path = zed::node_binary_path()
            .map_err(|e| format!("Failed to find node runtime path: {}", e))?;

        // The compiled distribution file generated by esbuild
        let server_script_path = "dist/server.js".to_string();

        Ok(zed::Command {
            command: node_path,
            args: vec![
                server_script_path,
                "--stdio".to_string(), // Forces Node to utilize standard system pipes
            ],
            env: Vec::new(),
        })
    }
}

// Register the initialized struct with the host WebAssembly wrapper runtime
zed::register_extension!(GitPerfectExtension);
